### ISSUE TITLE
Clicking save doesn't save Activities or Plans

### ISSUE THREAD

**Issue by micolss** [Loderian/Activities#1]
I'm evaluating this Plugin but can't get the plugin to save after creating an Activity or a Plan.
What am I doing wrong?

/Micke

**Comment by Loderian** [comment]
As I understand it, you have created an activity (and plan) but you cant update it afterwards.
Do you get an admin notice (a bar with colored left side at the top of the page) when you click save? 
And if so what does it say?
Also can you create/update/delete locations?

**Comment by four2six** [comment]
Hi, I probably have the same issue with creating an activity. The admin notice is "An error occured creating activity:" and the activity name that was entered.
Any ideas?
Jan
edit: i can create locations
edit: i can't create plans. "An error occured creating plan"

**Comment by Loderian** [comment]
@four2six Ok, so I see that it failed to insert the activity and plan into the database ($wpdb returned a false value). I need to read the response and/or errors from the database to help further. You can install "Query Monitor" plugin to see errors that occur when creating activities/plans.

**Comment by four2six** [comment]
Hi Mikal, 
thanks for your reply.
It's mainly these two errors:
Table 'usr_web592_1.wp498_activities_activity' doesn't exist
Table 'usr_adminuser_1.wp498_activities_plan' doesn't exist

I'm sure you get the hang of it. Below some more details... there's more Query details, but the error is always the same.

If you need to have more, let me know.

Thanks for your help!

Jan

---
When opening "Create New Activity":
Database Error: 
Query | Caller | Component | Error Message | Error Code
SELECT plan_id, name       FROM wp498_activities_plan |  
acts_get_items_map() | Plugin: activities | Table 'usr_adminuser_1.wp498_activities_plan' doesn't exist | 1146

Duplicate Queries:
Query | Count | Callers | Components | Potential Troublemakers
SELECT wp498_users.* FROM wp498_users INNER JOIN wp498_usermeta ON ( wp498_users.ID = wp498_usermeta.user_id ) WHERE 1=1 AND ( ( ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"administrator\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"editor\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"author\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"contributor\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"subscriber\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"translator\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"awpcp-moderator\"%' ) OR ( wp498_usermeta.meta_key = 'wp498_capabilities' AND wp498_usermeta.meta_value LIKE '%\"zwarfreshman\"%' ) ) ) ORDER BY user_login ASC
2 |  
Plugin: activities2 calls | WP_User_Query->query()2 calls


----
When trying to save new Activity "Nordic Walking"


SELECT COUNT(*)
FROM wp498_activities_activity
WHERE name = 'Nordic Walking'

Table 'usr_web592_1.wp498_activities_activity' doesn't exist


SELECT COUNT(*)
FROM wp498_activities_activity
WHERE name = 'Nordic Walking'

Table 'usr_web592_1.wp498_activities_activity' doesn't exist

etc.

**Comment by Loderian** [comment]
Thanks for the detailed reply! Seems like the db updater and installer is not in sync. I think my idea was that the installer would do the initial db tables (from version 1.0.0) and then the updater do all the later changes. But the installer sets the highest version without doing the required changes, and then the updater thinks it's up to date. I also found a stupid bug with installing the activity table itself.
I'll try to make a fix and test it this week (keep in mind this is a side/hobby project for me now).

**Comment by four2six** [comment]
Of course, take your time. I still would appreciate it, as it is just what i was looking for. Well, i guess it is, as i couldn't test it. But it looks promising.
Thank you for your work.
If there's anything i can do to help, let me know.

**Comment by Loderian** [comment]
I have published a new version of the plugin (1.1.3), the updater should add the missing tables. Tested core plugin functionality on a fresh wordpress install on my machine, it seems to be working now. Let me know if there are more problems.

**Comment by four2six** [comment]
Hi Mikal,
sorry for taking so long to test... the above problems seem to have gone. As i can't do updates, i reinstalled the plugin and it works when creating an activity and a plan.
A simple test with a future activity without a location and a plan and a button created to join that activity brings up another problem though: nothing happens when clicking the button. I know this is a different issue, if you want me to open a new one, let me know. 

Any idea what I'm doing wrong or how I could provide you with further information to solve it?
Thanks so much for your work!
Jan

**Comment by Loderian** [comment]
@four2six Thanks for testing Jan. I have made a new issue from your comment, I don't know if you got a notification. Seems like you have to subscribe to it if you want updates.
