### ISSUE TITLE
Join button does not work

### ISSUE THREAD

**Issue by Loderian** [Loderian/Activities#2]
Hi Mikal,
sorry for taking so long to test... the above problems seem to have gone. As i can't do updates, i reinstalled the plugin and it works when creating an activity and a plan.
A simple test with a future activity without a location and a plan and a button created to join that activity brings up another problem though: nothing happens when clicking the button. I know this is a different issue, if you want me to open a new one, let me know. 

Any idea what I'm doing wrong or how I could provide you with further information to solve it?
Thanks so much for your work!
Jan

_Originally posted by @four2six in https://github.com/Loderian/Activities/issues/1#issuecomment-612364625_

**Comment by Loderian** [comment]
Seems like the javascript related to the join button is outdated, no longer supported by browsers (atleast not in Firefox and Chrome). I must have used some old functionality when I implemented it.

**Comment by four2six** [comment]
What's the action/function behind it? Actually i wouldn't prefer a button but something like a link/image that changes status.

**Comment by Loderian** [comment]
Ajax to run php for database update and javascript to update button text/html before and after joining. I used the namedItem function, to find the button, which doesn't exist for the new return value when getting children of the join form. 

I could expand the shortcode with a join link/image option. You would have to provide image links in the shortcode, one for joining and one for leaving (or maybe a join only option).

**Comment by four2six** [comment]
i another surrounding i used submit() as in 
<input type="checkbox" onchange="this.form.submit()">
maybe helps, even though i didn't check it on all environments

**Comment by four2six** [comment]
Hi Mikal,
i noticed you did solved the issue. Thanks a lot!
Jan
