### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by four2six** [Loderian/Activities#4]
I translated the plugin to german, let me know if you're interested in adding it. And in case, let me know how i can send it to you.
Jan

**Comment by Loderian** [comment]
It would be best if it can be added here: https://translate.wordpress.org/projects/wp-plugins/activities/

**Comment by four2six** [comment]
that page won't let me upload the activities-de_DE.po file? or am I not getting something?

**Comment by Loderian** [comment]
https://translate.wordpress.org/projects/wp-plugins/activities/dev/de/default/import-translations/ for 'regular' non-formal german (Found at: German -> Development (trunk) -> Import Translations (at the bottom of the page))

**Comment by four2six** [comment]
i was blind, sorry. 
i uploaded it.
